// <auto-generated/> (esto omite validación de StyleCop).
// ReSharper disable once CheckNamespace
namespace log4net.ObjectRenderer
{
    using System;
    using System.IO;

    /// <summary>
    /// Renderiza una excepción como JSON.
    /// </summary>
    internal class ExceptionRender : IObjectRenderer
    {
        /// <summary>
        /// Renderiza una excepción como JSON.
        /// </summary>
        /// <param name="rendererMap">The renderMap.</param>
        /// <param name="obj">Excepción a renderizar como JSON.</param>
        /// <param name="writer">The writer.</param>
        public void RenderObject(RendererMap rendererMap, object obj, TextWriter writer)
        {
            writer.Write((obj as Exception).ToJson());
        }
    }
}